ahome/urls.py
from django.urls import path
from . import views

app_name = 'ahome'

urlpatterns = [
    path('', views.apply_base , name='apply_base'),
    path('pjmanage/', views.pj_list , name='pj_list'),
    path('<int:abase_id>/', views.apply_detail , name='apply_detail'),
    path('ibju/', views.ibju_data , name='ibju_list'),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path

from pybo.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('ahome/', include('ahome.urls')),
    path('', base_views.index, name='index'),  # '/' 에 해당되는 path
]

pybo/urls.py
from django.urls import path

from .views import base_views, question_views, answer_views, comment_views, vote_views

app_name = 'pybo'

urlpatterns = [
    # base_views.py
    path('', base_views.index, name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),

    # question_views.py
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),

    # answer_views.py
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),

    # comment_views.py
    path('comment/create/question/<int:question_id>/', comment_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/', comment_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/', comment_views.comment_delete_question, name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer, name='comment_delete_answer'),

    # vote_views.py
    path('vote/question/<int:question_id>/', vote_views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/', vote_views.vote_answer, name='vote_answer'),
]

ahome/models.py
from django.db import models

class Abase(models.Model):
    관리번호 = models.BigIntegerField(blank=True, null=True)
    모집공고일 = models.DateField(blank=True, null=True)
    단지명 = models.TextField(blank=True, null=True)
    주택구분 = models.TextField(blank=True, null=True)
    민영국민 = models.TextField(blank=True, null=True)
    분양구분 = models.TextField(blank=True, null=True)
    지역 = models.TextField(blank=True, null=True)
    자치구 = models.TextField(blank=True, null=True)
    주소지 = models.TextField(blank=True, null=True)
    세대수 = models.BigIntegerField(blank=True, null=True)
    계약시작일 = models.DateField(blank=True, null=True)
    계약종료일 = models.DateField(blank=True, null=True)
    건설사 = models.TextField(blank=True, null=True)
    시행사 = models.TextField(blank=True, null=True)
    입주시기 = models.TextField(blank=True, null=True)
    입주년도 = models.BigIntegerField(blank=True, null=True)
    모집공고월 = models.DateField(blank=True, null=True)


    def __str__(self):
        return self.단지명


class Adetail(models.Model):
    관리번호 = models.BigIntegerField(blank=True, null=True)
    모집공고일 = models.DateField(blank=True, null=True)
    지역 = models.TextField(blank=True, null=True)
    단지명 = models.TextField(blank=True, null=True)
    세대수 = models.BigIntegerField(blank=True, null=True)
    타입 = models.TextField(blank=True, null=True)
    공급면적 = models.TextField(blank=True, null=True)
    평형 = models.BigIntegerField(blank=True, null=True)
    타입세대수 = models.BigIntegerField(blank=True, null=True)
    타입최고가 = models.TextField(blank=True, null=True)
    공급평당가 = models.TextField(blank=True, null=True)
    모집공고월 = models.DateField(blank=True, null=True)
    abase = models.ForeignKey(Abase, on_delete=models.CASCADE)

    # class Meta:
    #     managed = False
    #     db_table = 'applydetail'

    def __str__(self):
        return self.단지명 + self.타입

class Pjmanage(models.Model):
    pjcode = models.CharField(max_length=10)
    optcode = models.CharField(max_length=10,null=True, blank=True)
    pjname = models.TextField(null=True, blank=True)
    end_day = models.DateTimeField(null=True, blank=True)
    come_day = models.DateTimeField(null=True, blank=True)
    dead_day = models.DateTimeField(null=True, blank=True)
    first_rate = models.FloatField()
    finance_rate = models.FloatField()
    end_rate = models.FloatField()
    end_profit = models.IntegerField()
    diff_ing = models.FloatField()
    fund = models.IntegerField()
    pf_remain = models.IntegerField()
    cash_year = models.IntegerField()
    cash_all = models.IntegerField()


class Ibju(models.Model):
    구분 = models.CharField(max_length=20)
    단지명 = models.CharField(max_length=50,null=True, blank=True)
    소재지 = models.CharField(max_length=50, null=True, blank=True)
    입주시기 = models.DateTimeField(null=True, blank=True)
    세대수 = models.IntegerField()
    매매시세 = models.IntegerField()
    평당분양가 = models.IntegerField()
    시공사 = models.CharField(max_length=20)
    시도 = models.CharField(max_length=20)
    자치구 = models.CharField(max_length=20)
    시도자치구 = models.CharField(max_length=20)
    기준월 = models.DateTimeField(null=True, blank=True)
    년 = models.IntegerField()

ahome/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from ahome.models import Abase, Adetail, Pjmanage, Ibju
from django.utils import timezone
from django.db.models import Q


# @login_required(login_url='common:login')
def apply_base(request):
    kw = request.GET.get('kw', '')
    abase = Abase.objects.order_by('-모집공고일')
    if kw:
        abase = abase.filter(
            Q(지역__icontains=kw) |
            Q(건설사__icontains=kw)
        ).distinct()
    context = {'abase': abase, 'kw': kw}
    return render(request, 'ahome/apply_base.html', context)


def apply_detail(request, abase_id):
    abase = Abase.objects.get(id=abase_id)
    details = abase.adetail_set.all()
    context = {
        'abase': abase,
        'details': details
    }
    return render(request, 'ahome/apply_detail.html', context)

def pj_list(request):
    lists = Pjmanage.objects.all()
    context = { 'pjlist' : lists }
    return render(request, 'ahome/pj_manage.html', context)

def ibju_data(request):
    kw = request.GET.get('kw', '')
    ibju_list = Ibju.objects.order_by('입주시기')
    if kw:
        ibju_list = ibju_list.filter(
            Q(구분__icontains=kw) |
            Q(시도__icontains=kw) |
            Q(자치구__icontains=kw) |
            Q(시공사__icontains=kw)
        ).distinct()
    context = { 'ibju_list' : ibju_list, 'kw': kw }

    return render(request, 'ahome/ibju_list.html', context)

templates/ahome/apply_base.html
{% extends 'base.html' %}

{% block content %}

<div class="container my-3">
    <!--검색기능-->
    <div class="col-4 input-group">
        <input type="text" class="form-control kw" value="{{ kw|default_if_none:'' }}">
        <div class="input-group-append">
            <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
        </div>
    </div>
    <table class="table table-striped" style="font-size:12px">
        <p style="font-size:9;">* 평당가는 타입별 최고가의 평당가의 평균가격임</p>
        <thead>
        <tr>
            <th>모집공고일</th>
            <th>단지명</th>
            <th>주택구분</th>
            <th>민영국민</th>
            <th>지역</th>
            <th>자치구</th>
            <th>주소지</th>
            <th>세대수</th>
            <th>계약종료일</th>
            <th>건설사</th>
            <th>시행사</th>
            <th>입주시기</th>
        </tr>
        </br>
        </thead>

        <tbody>
        {% for value in abase %}
        <tr>
            <td style="width:80px;"> {{ value.모집공고일|date:'y-m-d' }}</td>
            <td><a href="{% url 'ahome:apply_detail' value.id %}">{{ value.단지명 }}</a></td>
            <td> {{ value.주택구분 }}</td>
            <td style="width:50px;"> {{ value.민영국민 }}</td>
            <td style="width:50px;"> {{ value.지역 }}</td>
            <td> {{ value.자치구 }}</td>
            <td> {{ value.주소지 }}</td>
            <td> {{ value.세대수 }}</td>
            <td style="width:80px;"> {{ value.계약종료일|date:'y-m-d' }}</td>
            <td> {{ value.건설사 }}</td>
            <td> {{ value.시행사 }}</td>
            <td> {{ value.입주시기 }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

<!--kw를 get방식으로 요청하는 form추가-->
<form id="searchForm" method="get" action="{% url 'ahome:apply_base' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
</form>
{% endblock %}

{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $("#btn_search").on('click', function() {
        $("#kw").val($(".kw").val());
        $("#page").val(1);  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
        $("#searchForm").submit();
    });
});
</script>
{% endblock %}

templates/ahome/apply_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <table class="table table-striped" style="font-size:12px">
        <p style="font-size:9;">* 평당가는 타입별 최고가의 평당가의 평균가격임</p>
        <thead>
        <tr>
            <th>모집공고일</th>
            <th>지역</th>
            <th>단지명</th>
            <th>타입</th>
            <th>공급면적</th>
            <th>평형</th>
            <th>타입세대수</th>
            <th>타입최고가</th>
            <th>공급평당가</th>
        </tr></br>
         </thead>
        <tbody>
        {% for value in details %}
        <tr>
            <td> {{ value.모집공고일 }}</td>
            <td> {{ value.지역 }}</td>
            <td> {{ value.단지명 }}</td>
            <td> {{ value.타입 }}</td>
            <td> {{ value.공급면적 }}</td>
            <td> {{ value.평형 }}</td>
            <td> {{ value.타입세대수 }}</td>
            <td> {{ value.타입최고가 }}</td>
            <td> {{ value.계약종료일 }}</td>
            <td> {{ value.공급평당가 }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

templates/ahome/ibju_list.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}
<div class="container my-3">
    <div class="row justify-content-between my-3">
        <div class="col-4 input-group">
            <input type="text" class="form-control kw" value="{{ kw|default_if_none:'' }}">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
            </div>
        </div>
    </div>
    <table class="table table-striped" style="font-size:12px">
        <thead>
        <tr class="text-center thead-dark">
            <th style="width:100px;">구분</th>
            <th style="width:100px;">시도</th>
            <th style="width:80px;">자치구</th>
            <th>단지명</th>
            <th>세대수</th>
            <th>입주시기</th>
            <th style="width:200px;">소재지</th>
            <th>시공사</th>
        </tr>
        </thead>
        <tbody>
        {% for value in ibju_list %}
        <tr>
            <td> {{ value.구분 }}</td>
            <td> {{ value.시도 }}</td>
            <td> {{ value.자치구 }}</td>
            <td> {{ value.단지명 }}</td>
            <td> {{ value.세대수 }}</td>
            <td> {{ value.입주시기|date:'y-m' }}</td>
            <td> {{ value.소재지 }}</td>
            <td> {{ value.시공사 }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

<!--kw를 get방식으로 요청하는 form추가-->
<form id="searchForm" method="get" action="{% url 'ahome:ibju_list' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
</form>
{% endblock %}

{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $("#btn_search").on('click', function() {
        $("#kw").val($(".kw").val());
        $("#page").val(1);  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
        $("#searchForm").submit();
    });
});
</script>
{% endblock %}

templates/ahome/pj_manage.html
{% extends 'base.html' %}
{% load humanize %}
{% block content %}

<div class="container">
    <table class="table table-striped" style="font-size:12px;">
        <thead class="thead-dark">
        <tr>
            <th>PJ코드</th>
            <th>옵션코드</th>
            <th>사업명</th>
            <th>준공</th>
            <th>입주</th>
            <th>책준</th>
            <th>원가율(최초)</th>
            <th>원가율(재무)</th>
            <th>원가율(전망)</th>
            <th>전망이익</th>
            <th>공정차이</th>
            <th>매출채권</th>
            <th>PF잔액</th>
            <th>자금(당해)</th>
            <th>자금(누계)</th>
        </tr>
        </br>
        </thead>

        <tbody>
        {% for list in pjlist %}
        <tr>
            <td> {{ list.pjcode }} </td>
            <td> {{ list.optcode }} </td>
            <td> {{ list.pjname }} </td>
            <td> {{ list.end_day|date:'y-m' }}</td>
            <td> {{ list.come_day|date:'y-m' }}</td>
            <td> {{ list.dead_day|date:'y-m' }}</td>
            <td> {{ list.first_rate }}</td>
            <td> {{ list.finance_rate }}</td>
            <td> {{ list.end_rate }}</td>
            <td> {{ list.end_profit|intcomma }}</td>
            <td> {{ list.diff_ing }}</td>
            <td> {{ list.fund | intcomma }}</td>
            <td> {{ list.pf_remain|intcomma }}</td>
            <td> {{ list.cash_year |intcomma }}</td>
            <td> {{ list.cash_all | intcomma }}</td>
        <tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}